### ISSUE TITLE
File icons instead of folder icons

### ISSUE THREAD

**Issue by gaurav-nelson** [gabriel-rh/topic-maps-explorer#2]
![image](https://github.com/gabriel-rh/topic-maps-explorer/assets/23069445/4a0edc19-abe5-46dc-987e-d160032c31e6)

All assemblies and modules files have folder icon. It would make sense to list them with file icons. Bonus points if we get different icons for Assemblies and modules.

**Comment by gabriel-rh** [comment]
@gaurav-nelson I actually had used icons initially, but I wanted an expand/collapse for the assembly, and I cannot control the Icon for the >, so I had to go with an indented character A for assemblies - then it no longer made sense to have icons for the modules, so I switched them to character as well...

If you can figure out a way to do it, that would be great...it is outside my capabilities..

**Comment by gabriel-rh** [comment]
I missed the bit about folder icons - in my screenshot in the README, they don't appear at all but maybe they are just hidden, and whatever theme you have is showing them, while my setup isn't?

Need to figure out what is going on here alright...

**Comment by gaurav-nelson** [comment]
Thanks. It could be the theme. I'll turn it off and check.

**Comment by gaurav-nelson** [comment]
That was theme. Thank you.
