### ISSUE TITLE
Support for top level `topic_map` file

### ISSUE THREAD

**Issue by gaurav-nelson** [gabriel-rh/topic-maps-explorer#3]
The `rhacs-docs` branch in the `openshift-docs` repository uses top level `_topic_map.yml` file. Right now the extension doesn't load anything. Please add support for top level topic map file as well.

**Comment by gabriel-rh** [comment]
@gaurav-nelson I think it might be easier to just migrate acs to using the _topic_maps folder?

**Comment by gaurav-nelson** [comment]
Thank you @gabriel-rh Yes we did that.
